//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampSoftPractical.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SalesPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesPerson()
        {
            this.SalesProducts = new HashSet<SalesProduct>();
        }
        
        [Required(ErrorMessage ="Enter a Value!")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter a Value!")]
        public Nullable<int> SalesPersonCategoryId { get; set; }
        [Required(ErrorMessage = "Enter a Value!")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Enter a Value!")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Enter a Value!")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [Required(ErrorMessage = "Enter a Value!")]
        public Nullable<decimal> Salary { get; set; }
        [Required(ErrorMessage = "Enter a Value!")]
        public Nullable<bool> IsMarried { get; set; }
        [Required(ErrorMessage = "Enter a Value!")]
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SalesPersonCategory SalesPersonCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesProduct> SalesProducts { get; set; }
    }
}
